var hierarchy =
[
    [ "Crunch::Around< Target, Tolerance >", "structCrunch_1_1Around.html", null ],
    [ "Crunch::messages::ArrayField< Id, ElementType, MaxSize, Validators >", "classCrunch_1_1messages_1_1ArrayField.html", null ],
    [ "Crunch::Buffer< Message, Integrity, Serdes, N >", "structCrunch_1_1Buffer.html", null ],
    [ "Crunch::integrity::CRC16", "structCrunch_1_1integrity_1_1CRC16.html", null ],
    [ "Crunch::EqualTo< Threshold >", "structCrunch_1_1EqualTo.html", null ],
    [ "Crunch::Error", "structCrunch_1_1Error.html", null ],
    [ "Crunch::Even", "structCrunch_1_1Even.html", null ],
    [ "Crunch::False", "structCrunch_1_1False.html", null ],
    [ "std::false_type", null, [
      [ "Crunch::detail::is_buffer< T >", "structCrunch_1_1detail_1_1is__buffer.html", null ],
      [ "Crunch::fields::is_scalar< T >", "structCrunch_1_1fields_1_1is__scalar.html", null ],
      [ "Crunch::fields::is_string< T >", "structCrunch_1_1fields_1_1is__string.html", null ],
      [ "Crunch::messages::is_array_field< T >", "structCrunch_1_1messages_1_1is__array__field.html", null ],
      [ "Crunch::messages::is_field< T >", "structCrunch_1_1messages_1_1is__field.html", null ]
    ] ],
    [ "Crunch::messages::Field< Id, PresenceValidator, Type >", "classCrunch_1_1messages_1_1Field.html", null ],
    [ "Crunch::FixedString< N >", "structCrunch_1_1FixedString.html", null ],
    [ "Crunch::GreaterThan< Threshold >", "structCrunch_1_1GreaterThan.html", null ],
    [ "Crunch::GreaterThanOrEqualTo< Threshold >", "structCrunch_1_1GreaterThanOrEqualTo.html", null ],
    [ "Crunch::IsFinite", "structCrunch_1_1IsFinite.html", null ],
    [ "Crunch::Length< N >", "structCrunch_1_1Length.html", null ],
    [ "Crunch::LengthAtLeast< N >", "structCrunch_1_1LengthAtLeast.html", null ],
    [ "Crunch::LengthAtMost< N >", "structCrunch_1_1LengthAtMost.html", null ],
    [ "Crunch::LessThan< Threshold >", "structCrunch_1_1LessThan.html", null ],
    [ "Crunch::LessThanOrEqualTo< Threshold >", "structCrunch_1_1LessThanOrEqualTo.html", null ],
    [ "Crunch::Negative", "structCrunch_1_1Negative.html", null ],
    [ "Crunch::integrity::None", "structCrunch_1_1integrity_1_1None.html", null ],
    [ "Crunch::None", "structCrunch_1_1None.html", null ],
    [ "Crunch::NotEqualTo< Threshold >", "structCrunch_1_1NotEqualTo.html", null ],
    [ "Crunch::NotZero", "structCrunch_1_1NotZero.html", null ],
    [ "Crunch::NullTerminated", "structCrunch_1_1NullTerminated.html", null ],
    [ "Crunch::Odd", "structCrunch_1_1Odd.html", null ],
    [ "Crunch::OneOf< Values >", "structCrunch_1_1OneOf.html", null ],
    [ "Crunch::Optional", "structCrunch_1_1Optional.html", null ],
    [ "Crunch::integrity::Parity", "structCrunch_1_1integrity_1_1Parity.html", null ],
    [ "Crunch::Positive", "structCrunch_1_1Positive.html", null ],
    [ "Crunch::Required", "structCrunch_1_1Required.html", null ],
    [ "Crunch::fields::Scalar< ScalarType, Validators >", "classCrunch_1_1fields_1_1Scalar.html", null ],
    [ "Crunch::serdes::StaticLayout< Alignment >", "structCrunch_1_1serdes_1_1StaticLayout.html", null ],
    [ "Crunch::fields::String< MaxSize, Validators >", "classCrunch_1_1fields_1_1String.html", null ],
    [ "Crunch::StringEquals< S >", "structCrunch_1_1StringEquals.html", null ],
    [ "Crunch::StringNotEquals< S >", "structCrunch_1_1StringNotEquals.html", null ],
    [ "Crunch::serdes::TlvLayout", "structCrunch_1_1serdes_1_1TlvLayout.html", null ],
    [ "Crunch::True", "structCrunch_1_1True.html", null ],
    [ "std::true_type", null, [
      [ "Crunch::detail::is_buffer< Buffer< Message, Integrity, Serdes, N > >", "structCrunch_1_1detail_1_1is__buffer_3_01Buffer_3_01Message_00_01Integrity_00_01Serdes_00_01N_01_4_01_4.html", null ],
      [ "Crunch::fields::is_scalar< Scalar< ScalarType, Validators... > >", "structCrunch_1_1fields_1_1is__scalar_3_01Scalar_3_01ScalarType_00_01Validators_8_8_8_01_4_01_4.html", null ],
      [ "Crunch::fields::is_string< String< MaxSize, V... > >", "structCrunch_1_1fields_1_1is__string_3_01String_3_01MaxSize_00_01V_8_8_8_01_4_01_4.html", null ],
      [ "Crunch::messages::is_array_field< ArrayField< Id, E, M, V... > >", "structCrunch_1_1messages_1_1is__array__field_3_01ArrayField_3_01Id_00_01E_00_01M_00_01V_8_8_8_01_4_01_4.html", null ],
      [ "Crunch::messages::is_field< Field< Id, P, T > >", "structCrunch_1_1messages_1_1is__field_3_01Field_3_01Id_00_01P_00_01T_01_4_01_4.html", null ]
    ] ],
    [ "Crunch::Unique", "structCrunch_1_1Unique.html", null ],
    [ "Crunch::serdes::Varint", "structCrunch_1_1serdes_1_1Varint.html", null ]
];