load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "arrays_test",
    srcs = ["test_arrays.cpp"],
    deps = [
        "//include:crunch",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "map_field_test",
    srcs = ["test_map_field.cpp"],
    deps = [
        "//include:crunch",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "scalars_test",
    srcs = ["test_scalars.cpp"],
    deps = [
        "//include:crunch",
        "@catch2//:catch2_main",
    ],
)

cc_test(
    name = "string_test",
    srcs = ["test_string.cpp"],
    deps = [
        "//include:crunch",
        "@catch2//:catch2_main",
    ],
)
