load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "message_concept_validation_test",
    srcs = ["test_message_concept_validation.cpp"],
    deps = [
        "//include:crunch",
        "@catch2//:catch2_main",
    ],
)
