load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "crunch_header_test",
    srcs = ["test_crunch_header.cpp"],
    deps = [
        "//include:crunch",
        "@catch2//:catch2_main",
    ],
)
